### ISSUE TITLE
[SERIOUS BUG] 7potatos are not 7ms nor 7bits

### ISSUE THREAD

**Issue by albertdb** [jakubknejzlik/unit-converter#1]
Hi,

I found a parsing bug. Whenever you try to convert anything with a non "acceptable" unit (eg. `7potatos`, or `7M`, that is, 7 months), the library considers it as miliseconds or bits, depending on the `to` unit.

Could you please fix it?

Thanks

**Comment by jakubknejzlik** [comment]
Hi, I've fixed the in `v1.0.3` and also moved it to typescript in `v1.1.0`
